routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Config;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);

Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });

//Front Office
Route::get('/', 'HomeController@index')->name('home');
Route::get('/mentions-legales', 'HomeController@legales')->name('mentions-legales');
Route::get('/cgv', 'HomeController@cgv')->name('cgv');
Route::get('/banned', 'BannedController@index')->name('banned');


Route::post('/search', 'VehicleController@search')->name('get_vehicles');
Route::get('/search/{agency_id}/{date_time_departure}/{date_time_end}/{order}',
            'VehicleController@search')->name('get_vehicles_order');


Route::get('/order/store/{vehicle_id}/{date_time_departure}/{date_time_end}',
'OrderController@store')->name('order_store');

Route::get('/account', 'UserController@index')->name('account');
Route::post('/account/{id}', 'UserController@update')->name('update_account');

Route::get('/orders', 'OrderController@index')->name('orders');


Route::post('/contact', 'ContactController@send')->name('contact');
Route::get('/contact', 'ContactController@index')->name('contact');

//For test
Route::get('/crash_test', function(){
    $users = Config::get('users');
    dd($users);

});

//Back Office
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
     // Agencies
     Route::get('/agencies', 'AgencyController@index')->name('agencies_index');
     Route::get('/agencies/create', 'AgencyController@create')->name('agencies_create');
     Route::post('/agencies/store', 'AgencyController@store')->name('agencies_store');
     Route::get('/agencies/edit/{id}', 'AgencyController@edit')->name('agencies_edit');
     Route::post('/agencies/update/{id}', 'AgencyController@update')->name('agencies_update');
     Route::get('/agencies/destroy/{id}', 'AgencyController@destroy')->name('agencies_destroy');
     // Users
     Route::get('/', 'UserController@index')->name('home');
     Route::get('/users', 'UserController@index')->name('users_index');
     Route::get('/users/create', 'UserController@create')->name('user_create');
     Route::post('/users/store', 'UserController@store')->name('user_store');
     Route::get('/users/edit/{id}', 'UserController@edit')->name('user_edit');
     Route::post('/users/update/{id}', 'UserController@update')->name('user_update');
     Route::get('/users/destroy/{id}', 'UserController@destroy')->name('user_destroy');
     // Brands
     Route::get('/brands', 'BrandController@index')->name('brands_index');
     Route::get('/brands/create', 'BrandController@create')->name('brands_create');
     Route::post('/brands/store', 'BrandController@store')->name('brands_store');
     Route::get('/brands/edit/{id}', 'BrandController@edit')->name('brands_edit');
     Route::post('/brands/update/{id}', 'BrandController@update')->name('brands_update');
     Route::get('/brands/destroy/{id}', 'BrandController@destroy')->name('brands_destroy');
    // Vmodels
     Route::get('/models', 'VmodelController@index')->name('vmodels_index');
     Route::get('/models/create', 'VmodelController@create')->name('vmodels_create');
     Route::post('/models/store', 'VmodelController@store')->name('vmodels_store');
     Route::get('/models/edit/{id}', 'VmodelController@edit')->name('vmodels_edit');
     Route::post('/models/update/{id}', 'VmodelController@update')->name('vmodels_update');
     Route::get('/models/destroy/{id}', 'VmodelController@destroy')->name('vmodels_destroy');
     // Vehicles
     Route::get('/vehicles', 'VehicleController@index')->name('vehicles_index');
     Route::get('/vehicles/create', 'VehicleController@create')->name('vehicles_create');
     Route::post('/vehicles/store', 'VehicleController@store')->name('vehicles_store');
     Route::get('/vehicles/edit/{id}', 'VehicleController@edit')->name('vehicles_edit');
     Route::post('/vehicles/update/{id}', 'VehicleController@update')->name('vehicles_update');
     Route::get('/vehicles/destroy/{id}', 'VehicleController@destroy')->name('vehicles_destroy');
     // Orders
     Route::get('/orders', 'OrderController@index')->name('orders_index');
     Route::get('/orders/create', 'OrderController@create')->name('orders_create');
     Route::post('/orders/store', 'OrderController@store')->name('orders_store');
     Route::get('/orders/edit/{id}', 'OrderController@edit')->name('orders_edit');
     Route::post('/orders/update/{id}', 'OrderController@update')->name('orders_update');
     Route::get('/orders/destroy/{id}', 'OrderController@destroy')->name('orders_destroy');

});

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    /**
     * Get agency.
     */
    public function agency()
    {
        return $this->belongsTo('App\Agency', 'agency_id');
    }

    /**
     * Get vmodel.
     */
    public function vmodel()
    {
        return $this->belongsTo('App\Vmodel', 'vmodel_id');
    }

    /**
     * Get orders.
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/Admin/VehicleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Vmodel;
use App\Vehicle;
use App\Agency;
use Illuminate\Http\Request;

class VehicleController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('verified');
        $this->middleware('admin');
        $this->middleware('banned');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $vehicles = Vehicle::all();
      return view('admin.vehicles.index', ["vehicles"=>$vehicles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $agencies = Agency::all();
      $vmodels = Vmodel::all();
      return view('admin.vehicles.create', ["agencies" => $agencies, "vmodels" => $vmodels]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'daily_price' => 'required|numeric',
        'vmodel_id' => 'required|numeric',
        'agency_id' => 'required|numeric',
       ]);
      $vehicle = new Vehicle;
      $vehicle->daily_price = $request->daily_price;
      $vehicle->vmodel_id = $request->vmodel_id;
      $vehicle->agency_id = $request->agency_id;
      $vehicle->save();
      return redirect()->to('/admin/vehicles')->with('success','Vehicle crée avec success !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(Vehicle $vehicle)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Vehicle $vehicle)
    {
      $id = request()->route('id');
      $vehicle = Vehicle::find($id);
      $agencies = Agency::all();
      $vmodels = Vmodel::all();
      return view('admin.vehicles.edit', ["vehicle"=>$vehicle, "agencies" => $agencies, "vmodels" => $vmodels]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vehicle $vehicle)
    {
      $request->validate([
        'daily_price' => 'required|numeric',
        'vmodel_id' => 'required|numeric',
        'agency_id' => 'required|numeric',
       ]);
      $id = request()->route('id');
      $vehicle = Vehicle::find($id);
      $vehicle->daily_price = $request->daily_price;
      $vehicle->vmodel_id = $request->vmodel_id;
      $vehicle->agency_id = $request->agency_id;
      $vehicle->save();
      return redirect()->to('/admin/vehicles')->with('success','Vehicle modifié avec success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
      $id = request()->route('id');
      $vehicle = Vehicle::destroy($id);
      return redirect()->to('/admin/vehicles')->with('success','Vehicle supprimé avec success !');

    }
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use App\Agency;
use App\Vehicle;
use Illuminate\Validation\Rule;
use Illuminate\Http\Request;

class VehicleController extends Controller
{    
    /**
    * Create a new controller instance.
    *
    * @return void
    */
   public function __construct()
   {
       $this->middleware('auth');
       $this->middleware('verified');
       $this->middleware('banned');
   }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Display a listing of the resource from search.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $request->validate([
            'date_time_departure' => 'date',
            'date_time_end' => 'date',
            'agency_id' => 'numeric',
            'order' => [
            Rule::in(['Desc', 'Asc']),
            ],  
           ]);
           if ($request->date_time_departure < date("Y-m-d") ||  $request->date_time_departure > $request->date_time_end) {
            return redirect()->to('/')->with('error','Date de départ doit être superieur à la date du jour et date de retour superieur à la date de départ !');
          }
        $agencies = Agency::all();
        $list = DB::table('vehicles')
        ->join('orders', 'vehicles.id', '=', 'orders.vehicle_id')
        ->whereNotBetween('orders.date_time_departure', [$request->date_time_departure, $request->date_time_end])
        ->whereNotBetween('orders.date_time_end', [$request->date_time_departure, $request->date_time_end])
        ->where('vehicles.agency_id', $request->agency_id)
        ->select('vehicles.id')
        ->get()->pluck('id')->toArray();

        if(empty($list)){
            return redirect()->to('/')->with('error','Aucun véhicule n\'est disponible !');
        }
        $diff = strtotime($request->date_time_departure) - strtotime($request->date_time_end); 
        $days = abs(round($diff / 86400));
        if($request->order != ""){
            //dd('hello');
            switch ($request->order) {
                case 'Desc':
                        $vehicles = Vehicle::find($list)
                        ->sortByDesc('daily_price');
                    break;
                
                case 'Asc':
                        $vehicles = Vehicle::find($list)
                        ->sortBy('daily_price');
                    break;
            }
        }else{
            $vehicles = Vehicle::find($list)
            ->sortBy('daily_price');
        }

        //dd($vehicles);
         return view('home', ["agencies" => $agencies, 
                              "vehicles" => $vehicles, 
                              "date_time_departure" => $request->date_time_departure,
                              "date_time_end" => $request->date_time_end,
                              "days" => $days,
                              "order" => ["Desc", "Asc"]
                              ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(Vehicle $vehicle)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(Vehicle $vehicle)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vehicle $vehicle)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vehicle $vehicle)
    {
        //
    }
}

resources/views/admin/vehicles/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    @include('partials.admin.notif')
                    <form method="POST" action="{{ route('admin.vehicles_store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="siimple-form">
                        <div class="siimple-form-title">Créer un Véhicule</div>

                        <div class="siimple-form-field">
                          <label class="siimple-form-field-label">Agence: </label> 
                          <select name="agency_id" class="siimple-select siimple-select--fluid">
                            @foreach ($agencies as $agency)
                              <option value="{{ $agency->id }}">{{ $agency->title }}</option> 
                            @endforeach
                          </select>
                        </div>

                        <div class="siimple-form-field">
                          <label class="siimple-form-field-label">Modèle: </label> 
                          <select name="vmodel_id" class="siimple-select siimple-select--fluid">
                            @foreach ($vmodels as $vmodel)
                              <option value="{{ $vmodel->id }}">{{ $vmodel->title }}</option> 
                            @endforeach
                          </select>
                        </div>

                        <div class="siimple-form-field">
                            <div class="siimple-form-field-label">Prix</div>
                            <input type="text" name="daily_price" class="siimple-input siimple-input--fluid" value="">
                        </div>

                        <div class="form-field">
                            <input type="submit" class="siimple-btn siimple-btn--primary siimple-btn--fluid" value="Envoyer">
                        </div>
                    </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vehicles/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    @include('partials.admin.notif')
                    <form method="POST" action="{{ route('admin.vehicles_update', [$vehicle->id]) }}" enctype="multipart/form-data">
                    @csrf

                    <div class="siimple-form">
                        <div class="siimple-form-title">Modifier un Véhicule</div>

                        <div class="siimple-form-field">
                          <label class="siimple-form-field-label">Agence: </label> 
                          <select name="agency_id" class="siimple-select siimple-select--fluid">
                            @foreach ($agencies as $agency)
                              <option value="{{ $agency->id }}" @if($vehicle->agency_id == $agency->id) selected @endif>{{ $agency->title }}</option> 
                            @endforeach
                          </select>
                        </div>

                        <div class="siimple-form-field">
                          <label class="siimple-form-field-label">Modèle: </label> 
                          <select name="vmodel_id" class="siimple-select siimple-select--fluid">
                            @foreach ($vmodels as $vmodel)
                              <option value="{{ $vmodel->id }}" @if($vehicle->vmodel_id == $vmodel->id) selected @endif>{{ $vmodel->title }}</option> 
                            @endforeach
                          </select>
                        </div>

                        <div class="siimple-form-field">
                            <div class="siimple-form-field-label">Prix</div>
                            <input type="text" name="daily_price" class="siimple-input siimple-input--fluid" value="{{ $vehicle->daily_price }}">
                        </div>

                        <div class="form-field">
                            <input type="submit" class="siimple-btn siimple-btn--primary siimple-btn--fluid" value="Envoyer">
                        </div>
                    </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vehicles/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    <div class="bloc_add"><a href="{{ route('admin.vehicles_create') }}" class="siimple-btn siimple-btn--blue"><i class="fas fa-plus-circle"></i> Créer</a></div>
                    @include('partials.admin.notif')
                    <div class="admin_table">
                    <div class="siimple-table">
                      <div class="siimple-table-header">
                          <div class="siimple-table-row">
                              <div class="siimple-table-cell siimple-table-cell--1">ID</div>
                              <div class="siimple-table-cell siimple-table-cell--1">Marque</div>
                              <div class="siimple-table-cell siimple-table-cell--1">Photo</div>
                              <div class="siimple-table-cell siimple-table-cell--5">Titre</div>
                              <div class="siimple-table-cell siimple-table-cell--1">Agency</div>
                              <div class="siimple-table-cell siimple-table-cell--2"></div>
                              <div class="siimple-table-cell siimple-table-cell--2">Tarif journalier</div>
                              <div class="siimple-table-cell">Modifier</div>
                              <div class="siimple-table-cell">Supprimer</div>

                          </div>
                      </div>
                      <div class="siimple-table-body">
                        @foreach ($vehicles as $vehicle)
                          <div class="siimple-table-row">
                              <div class="siimple-table-cell">{{ $vehicle->id }}</div>
                              <div class="siimple-table-cell"><span class="tab_img brand"><img src="{{ $vehicle->vmodel->brand->photo }}" alt="{{ $vehicle->vmodel->brand->name }}" ></span></div>
                              <div class="siimple-table-cell"><span class="tab_img brand"><img src="{{ $vehicle->vmodel->photo }}" alt="img_{{ $vehicle->vmodel->id }}" ></span></div>
                              <div class="siimple-table-cell">{{ $vehicle->vmodel->title }}</div>
                              <div class="siimple-table-cell"><span class="tab_img agency"><img src="{{ $vehicle->agency->photo }}" alt="{{ $vehicle->agency->name }}" ></span></div>
                              <div class="siimple-table-cell">{{ $vehicle->agency->title }}</div>
                              <div class="siimple-table-cell">{{ number_format($vehicle->daily_price, 2) }} €</div>
                              <div class="siimple-table-cell"><a class="siimple-btn siimple-btn--green" href="{{ route('admin.vehicles_edit', [$vehicle->id]) }}"><i class="fas fa-edit"></i></a></div>
                              <div class="siimple-table-cell"><a class="siimple-btn siimple-btn--red" href="{{ route('admin.vehicles_destroy', [$vehicle->id]) }}"><i class="fas fa-trash-alt"></i></a></div>
                          </div>
                        @endforeach
                      </div>
                      </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection