routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Config;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);

Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });

//Front Office
Route::get('/', 'HomeController@index')->name('home');
Route::get('/mentions-legales', 'HomeController@legales')->name('mentions-legales');
Route::get('/cgv', 'HomeController@cgv')->name('cgv');
Route::get('/banned', 'BannedController@index')->name('banned');


Route::post('/search', 'VehicleController@search')->name('get_vehicles');
Route::get('/search/{agency_id}/{date_time_departure}/{date_time_end}/{order}',
            'VehicleController@search')->name('get_vehicles_order');


Route::get('/order/store/{vehicle_id}/{date_time_departure}/{date_time_end}',
'OrderController@store')->name('order_store');

Route::get('/account', 'UserController@index')->name('account');
Route::post('/account/{id}', 'UserController@update')->name('update_account');

Route::get('/orders', 'OrderController@index')->name('orders');


Route::post('/contact', 'ContactController@send')->name('contact');
Route::get('/contact', 'ContactController@index')->name('contact');

//For test
Route::get('/crash_test', function(){
    $users = Config::get('users');
    dd($users);

});

//Back Office
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
     // Agencies
     Route::get('/agencies', 'AgencyController@index')->name('agencies_index');
     Route::get('/agencies/create', 'AgencyController@create')->name('agencies_create');
     Route::post('/agencies/store', 'AgencyController@store')->name('agencies_store');
     Route::get('/agencies/edit/{id}', 'AgencyController@edit')->name('agencies_edit');
     Route::post('/agencies/update/{id}', 'AgencyController@update')->name('agencies_update');
     Route::get('/agencies/destroy/{id}', 'AgencyController@destroy')->name('agencies_destroy');
     // Users
     Route::get('/', 'UserController@index')->name('home');
     Route::get('/users', 'UserController@index')->name('users_index');
     Route::get('/users/create', 'UserController@create')->name('user_create');
     Route::post('/users/store', 'UserController@store')->name('user_store');
     Route::get('/users/edit/{id}', 'UserController@edit')->name('user_edit');
     Route::post('/users/update/{id}', 'UserController@update')->name('user_update');
     Route::get('/users/destroy/{id}', 'UserController@destroy')->name('user_destroy');
     // Brands
     Route::get('/brands', 'BrandController@index')->name('brands_index');
     Route::get('/brands/create', 'BrandController@create')->name('brands_create');
     Route::post('/brands/store', 'BrandController@store')->name('brands_store');
     Route::get('/brands/edit/{id}', 'BrandController@edit')->name('brands_edit');
     Route::post('/brands/update/{id}', 'BrandController@update')->name('brands_update');
     Route::get('/brands/destroy/{id}', 'BrandController@destroy')->name('brands_destroy');
    // Vmodels
     Route::get('/models', 'VmodelController@index')->name('vmodels_index');
     Route::get('/models/create', 'VmodelController@create')->name('vmodels_create');
     Route::post('/models/store', 'VmodelController@store')->name('vmodels_store');
     Route::get('/models/edit/{id}', 'VmodelController@edit')->name('vmodels_edit');
     Route::post('/models/update/{id}', 'VmodelController@update')->name('vmodels_update');
     Route::get('/models/destroy/{id}', 'VmodelController@destroy')->name('vmodels_destroy');
     // Vehicles
     Route::get('/vehicles', 'VehicleController@index')->name('vehicles_index');
     Route::get('/vehicles/create', 'VehicleController@create')->name('vehicles_create');
     Route::post('/vehicles/store', 'VehicleController@store')->name('vehicles_store');
     Route::get('/vehicles/edit/{id}', 'VehicleController@edit')->name('vehicles_edit');
     Route::post('/vehicles/update/{id}', 'VehicleController@update')->name('vehicles_update');
     Route::get('/vehicles/destroy/{id}', 'VehicleController@destroy')->name('vehicles_destroy');
     // Orders
     Route::get('/orders', 'OrderController@index')->name('orders_index');
     Route::get('/orders/create', 'OrderController@create')->name('orders_create');
     Route::post('/orders/store', 'OrderController@store')->name('orders_store');
     Route::get('/orders/edit/{id}', 'OrderController@edit')->name('orders_edit');
     Route::post('/orders/update/{id}', 'OrderController@update')->name('orders_update');
     Route::get('/orders/destroy/{id}', 'OrderController@destroy')->name('orders_destroy');

});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    /**
    * Get the vehicles models for the Brand.
    */
    public function vmodels()
    {
        return $this->hasMany('App\Vehicle');
    }

}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Brand;
use Illuminate\Http\Request;

class BrandController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('verified');
        $this->middleware('admin');
        $this->middleware('banned');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $brands = Brand::all();
      return view('admin.brands.index', ["brands"=>$brands]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.brands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'title' => 'required|alpha|unique:brands|max:60',
        'image' => 'required|image',
       ]);
      $brand = new Brand;
      $brand->title = $request->title;
      if ($request->hasFile('image')) {
        $image = $request->file('image');
        $input['imagename'] = time() . '.' . $image->getClientOriginalExtension();
        $destinationPath = public_path('/images/uploads/brands');
        $image->move($destinationPath, $input['imagename']);
        $brand->photo = '/images/uploads/brands/' . $input['imagename'];
      }
      $brand->save();
      return redirect()->to('/admin/brands')->with('success','Marque crée avec success !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $Brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $Brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
      $id = request()->route('id');
      $brand = Brand::find($id);
      return view('admin.brands.edit', ["brand"=>$brand]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
      $request->validate([
        'title' => 'required|alpha|max:60',
        'image' => 'image',
       ]);
      $id = request()->route('id');
      $brand = Brand::find($id);
      $brand->title = $request->title;
      if ($request->hasFile('image')) {
        $image = $request->file('image');
        $input['imagename'] = time() . '.' . $image->getClientOriginalExtension();
        $destinationPath = public_path('/images/uploads/brands/');
        $image->move($destinationPath, $input['imagename']);
        $brand->photo = '/images/uploads/brands/' . $input['imagename'];
      }
      $brand->save();
      return redirect()->to('/admin/brands')->with('success','Marque modifié avec success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
      $id = request()->route('id');
      $brand = Brand::destroy($id);
      return redirect()->to('/admin/brands')->with('success','Marque supprimé avec success !');

    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        //
    }
}

resources/views/admin/brands/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    @include('partials.admin.notif')
                    <form method="POST" action="{{ route('admin.brands_store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="siimple-form">
                        <div class="siimple-form-title">Créer une Marque</div>
                        <div class="siimple-form-field">
                            <div class="siimple-form-field-label">Titre</div>
                            <input type="text" name="title" class="siimple-input siimple-input--fluid" value="">
                        </div>

                        <div class="siimple-field">
                            <label class="siimple-form-field-label">Photo</label>
                            <input type="file" name="image" class="siimple-input siimple-input--fluid">
                        </div>

                        <div class="form-field">
                            <input type="submit" class="siimple-btn siimple-btn--primary siimple-btn--fluid" value="Envoyer">
                        </div>
                    </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/brands/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    @include('partials.admin.notif')
                    <form method="POST" action="{{ route('admin.brands_update', [$brand->id]) }}" enctype="multipart/form-data">
                    @csrf
                    <div class="siimple-form">
                        <div class="siimple-form-title">Modifier une Marque</div>
                        <div class="siimple-form-field">
                            <div class="siimple-form-field-label">Titre</div>
                            <input type="text" name="title" class="siimple-input siimple-input--fluid" value="{{ $brand->title }}">
                        </div>

                        <div class="siimple-field">
                            <label class="siimple-form-field-label">Photo</label>
                            <input type="file" name="image" class="siimple-input siimple-input--fluid">
                        </div>

                        <div class="form-field">
                            <input type="submit" class="siimple-btn siimple-btn--primary siimple-btn--fluid" value="Envoyer">
                        </div>
                    </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/brands/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="card">

                <div class="card-body">
                    <div class="bloc_add"><a href="{{ route('admin.brands_create') }}" class="siimple-btn siimple-btn--blue"><i class="fas fa-plus-circle"></i> Créer</a></div>
                    @include('partials.admin.notif')
                    <div class="admin_table">
                    <div class="siimple-table">
                      <div class="siimple-table-header">
                          <div class="siimple-table-row">
                              <div class="siimple-table-cell siimple-table-cell--1">ID</div>
                              <div class="siimple-table-cell siimple-table-cell--1">Photo</div>
                              <div class="siimple-table-cell siimple-table-cell--8">Titre</div>
                              <div class="siimple-table-cell">Modifier</div>
                              <div class="siimple-table-cell">Supprimer</div>

                          </div>
                      </div>
                      <div class="siimple-table-body">
                        @foreach ($brands as $brand)
                          <div class="siimple-table-row">
                              <div class="siimple-table-cell">{{ $brand->id }}</div>
                              <div class="siimple-table-cell"><span class="tab_img brand"><img src="{{ $brand->photo }}" alt="img_{{ $brand->id }}" ></span></div>
                              <div class="siimple-table-cell">{{ $brand->title }}</div>
                              <div class="siimple-table-cell"><a class="siimple-btn siimple-btn--green" href="{{ route('admin.brands_edit', [$brand->id]) }}"><i class="fas fa-edit"></i></a></div>
                              <div class="siimple-table-cell"><a class="siimple-btn siimple-btn--red" href="{{ route('admin.brands_destroy', [$brand->id]) }}"><i class="fas fa-trash-alt"></i></a></div>
                          </div>
                        @endforeach
                      </div>
                      </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection